#mycodes here
alias abc='cp && cd atCoder/ABC'
alias arc='cp && cd atCoder/ARC'
alias agc='cp && cd atCoder/AGC'
alias cp='cd ~/Desktop/competitiveProgramming/'
alias cf='cp && cd codeForces'
alias cc='cp && cd codeChef'
alias cfd3='cp && cd codeForces/div3'
alias cfd2='cp && cd codeForces/div2'
alias long='cp && cd codeChef/long'
alias cook='cp && cd codeChef/cook'
alias ltime='cp && cd codeChef/ltime'
alias cses='cp && cd cses'
alias leetcode='cp && cd LeetCode'
alias vj='cp && cd vjudge'
alias open='xdg-open .'
alias spoj='cp && cd Spoj'
alias home='cd ~'
alias dp='cp && cd dp'
alias template='cd ~/.vim/template'
alias dnd='cd ~/Downloads'
alias mvd='move_file(){ mv ~/Downloads/"$1" .;}; move_file'
#mycodes end here

